//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Kho.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Quan_Ly_KhoEntities : DbContext
    {
        public Quan_Ly_KhoEntities()
            : base("name=Quan_Ly_KhoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chitietnhap> Chitietnhaps { get; set; }
        public virtual DbSet<Chitietxuat> Chitietxuats { get; set; }
        public virtual DbSet<HangHoa> HangHoas { get; set; }
        public virtual DbSet<NCC> NCCs { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<PhieuXuat> PhieuXuats { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sua_CTN(string maCTN, string maPN, string maHH, Nullable<int> soLuong, Nullable<decimal> donGia)
        {
            var maCTNParameter = maCTN != null ?
                new ObjectParameter("maCTN", maCTN) :
                new ObjectParameter("maCTN", typeof(string));
    
            var maPNParameter = maPN != null ?
                new ObjectParameter("maPN", maPN) :
                new ObjectParameter("maPN", typeof(string));
    
            var maHHParameter = maHH != null ?
                new ObjectParameter("maHH", maHH) :
                new ObjectParameter("maHH", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("donGia", donGia) :
                new ObjectParameter("donGia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_CTN", maCTNParameter, maPNParameter, maHHParameter, soLuongParameter, donGiaParameter);
        }
    
        public virtual int sua_CTX(string maCTX, string maPX, string maHH, Nullable<int> soLuong, Nullable<decimal> donGia)
        {
            var maCTXParameter = maCTX != null ?
                new ObjectParameter("maCTX", maCTX) :
                new ObjectParameter("maCTX", typeof(string));
    
            var maPXParameter = maPX != null ?
                new ObjectParameter("maPX", maPX) :
                new ObjectParameter("maPX", typeof(string));
    
            var maHHParameter = maHH != null ?
                new ObjectParameter("maHH", maHH) :
                new ObjectParameter("maHH", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("donGia", donGia) :
                new ObjectParameter("donGia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_CTX", maCTXParameter, maPXParameter, maHHParameter, soLuongParameter, donGiaParameter);
        }
    
        public virtual int sua_HH(string maHH, string tenHH, string maNCC)
        {
            var maHHParameter = maHH != null ?
                new ObjectParameter("maHH", maHH) :
                new ObjectParameter("maHH", typeof(string));
    
            var tenHHParameter = tenHH != null ?
                new ObjectParameter("tenHH", tenHH) :
                new ObjectParameter("tenHH", typeof(string));
    
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("maNCC", maNCC) :
                new ObjectParameter("maNCC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_HH", maHHParameter, tenHHParameter, maNCCParameter);
        }
    
        public virtual int sua_NCC(string maNCC, string tenNCC, string diaChi, string sDT, string email)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("maNCC", maNCC) :
                new ObjectParameter("maNCC", typeof(string));
    
            var tenNCCParameter = tenNCC != null ?
                new ObjectParameter("tenNCC", tenNCC) :
                new ObjectParameter("tenNCC", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("diaChi", diaChi) :
                new ObjectParameter("diaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_NCC", maNCCParameter, tenNCCParameter, diaChiParameter, sDTParameter, emailParameter);
        }
    
        public virtual int sua_PN(string maPN, Nullable<System.DateTime> ngayNhap, Nullable<decimal> tongTien)
        {
            var maPNParameter = maPN != null ?
                new ObjectParameter("maPN", maPN) :
                new ObjectParameter("maPN", typeof(string));
    
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("ngayNhap", ngayNhap) :
                new ObjectParameter("ngayNhap", typeof(System.DateTime));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("tongTien", tongTien) :
                new ObjectParameter("tongTien", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_PN", maPNParameter, ngayNhapParameter, tongTienParameter);
        }
    
        public virtual int sua_PX(string maPX, Nullable<System.DateTime> ngayXuat, Nullable<decimal> tongTien)
        {
            var maPXParameter = maPX != null ?
                new ObjectParameter("maPX", maPX) :
                new ObjectParameter("maPX", typeof(string));
    
            var ngayXuatParameter = ngayXuat.HasValue ?
                new ObjectParameter("ngayXuat", ngayXuat) :
                new ObjectParameter("ngayXuat", typeof(System.DateTime));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("tongTien", tongTien) :
                new ObjectParameter("tongTien", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_PX", maPXParameter, ngayXuatParameter, tongTienParameter);
        }
    
        public virtual int them_CTN(string maCTN, string maPN, string maHH, Nullable<int> soLuong, Nullable<decimal> donGia)
        {
            var maCTNParameter = maCTN != null ?
                new ObjectParameter("maCTN", maCTN) :
                new ObjectParameter("maCTN", typeof(string));
    
            var maPNParameter = maPN != null ?
                new ObjectParameter("maPN", maPN) :
                new ObjectParameter("maPN", typeof(string));
    
            var maHHParameter = maHH != null ?
                new ObjectParameter("maHH", maHH) :
                new ObjectParameter("maHH", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("donGia", donGia) :
                new ObjectParameter("donGia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_CTN", maCTNParameter, maPNParameter, maHHParameter, soLuongParameter, donGiaParameter);
        }
    
        public virtual int them_CTX(string maCTX, string maPX, string maHH, Nullable<int> soLuong, Nullable<decimal> donGia)
        {
            var maCTXParameter = maCTX != null ?
                new ObjectParameter("maCTX", maCTX) :
                new ObjectParameter("maCTX", typeof(string));
    
            var maPXParameter = maPX != null ?
                new ObjectParameter("maPX", maPX) :
                new ObjectParameter("maPX", typeof(string));
    
            var maHHParameter = maHH != null ?
                new ObjectParameter("maHH", maHH) :
                new ObjectParameter("maHH", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("donGia", donGia) :
                new ObjectParameter("donGia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_CTX", maCTXParameter, maPXParameter, maHHParameter, soLuongParameter, donGiaParameter);
        }
    
        public virtual int them_NCC(string maNCC, string tenNCC, string diaChi, string sDT, string email)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("maNCC", maNCC) :
                new ObjectParameter("maNCC", typeof(string));
    
            var tenNCCParameter = tenNCC != null ?
                new ObjectParameter("tenNCC", tenNCC) :
                new ObjectParameter("tenNCC", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("diaChi", diaChi) :
                new ObjectParameter("diaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_NCC", maNCCParameter, tenNCCParameter, diaChiParameter, sDTParameter, emailParameter);
        }
    
        public virtual int them_PN(string maPN, Nullable<System.DateTime> ngayNhap, Nullable<decimal> tongTien)
        {
            var maPNParameter = maPN != null ?
                new ObjectParameter("maPN", maPN) :
                new ObjectParameter("maPN", typeof(string));
    
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("ngayNhap", ngayNhap) :
                new ObjectParameter("ngayNhap", typeof(System.DateTime));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("tongTien", tongTien) :
                new ObjectParameter("tongTien", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_PN", maPNParameter, ngayNhapParameter, tongTienParameter);
        }
    
        public virtual int them_PX(string maPX, Nullable<System.DateTime> ngayXuat, Nullable<decimal> tongTien)
        {
            var maPXParameter = maPX != null ?
                new ObjectParameter("maPX", maPX) :
                new ObjectParameter("maPX", typeof(string));
    
            var ngayXuatParameter = ngayXuat.HasValue ?
                new ObjectParameter("ngayXuat", ngayXuat) :
                new ObjectParameter("ngayXuat", typeof(System.DateTime));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("tongTien", tongTien) :
                new ObjectParameter("tongTien", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_PX", maPXParameter, ngayXuatParameter, tongTienParameter);
        }
    
        public virtual int them_TK(string acc, string pass)
        {
            var accParameter = acc != null ?
                new ObjectParameter("acc", acc) :
                new ObjectParameter("acc", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_TK", accParameter, passParameter);
        }
    
        public virtual ObjectResult<thongke_HH_Result> thongke_HH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongke_HH_Result>("thongke_HH");
        }
    
        public virtual ObjectResult<thongke_Nhap_Result> thongke_Nhap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongke_Nhap_Result>("thongke_Nhap");
        }
    
        public virtual ObjectResult<thongke_Xuat_Result> thongke_Xuat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongke_Xuat_Result>("thongke_Xuat");
        }
    
        public virtual ObjectResult<timkiem_HH1_Result> timkiem_HH1(string maHH)
        {
            var maHHParameter = maHH != null ?
                new ObjectParameter("maHH", maHH) :
                new ObjectParameter("maHH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<timkiem_HH1_Result>("timkiem_HH1", maHHParameter);
        }
    
        public virtual ObjectResult<timkiem_HH2_Result> timkiem_HH2(string tenHH)
        {
            var tenHHParameter = tenHH != null ?
                new ObjectParameter("tenHH", tenHH) :
                new ObjectParameter("tenHH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<timkiem_HH2_Result>("timkiem_HH2", tenHHParameter);
        }
    
        public virtual int xoa_CTN(string maCTN)
        {
            var maCTNParameter = maCTN != null ?
                new ObjectParameter("maCTN", maCTN) :
                new ObjectParameter("maCTN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_CTN", maCTNParameter);
        }
    
        public virtual int xoa_CTX(string maCTX)
        {
            var maCTXParameter = maCTX != null ?
                new ObjectParameter("maCTX", maCTX) :
                new ObjectParameter("maCTX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_CTX", maCTXParameter);
        }
    
        public virtual int xoa_HH(string maHH)
        {
            var maHHParameter = maHH != null ?
                new ObjectParameter("maHH", maHH) :
                new ObjectParameter("maHH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_HH", maHHParameter);
        }
    
        public virtual int xoa_NCC(string maNCC)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("maNCC", maNCC) :
                new ObjectParameter("maNCC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_NCC", maNCCParameter);
        }
    
        public virtual int xoa_PN(string maPN)
        {
            var maPNParameter = maPN != null ?
                new ObjectParameter("maPN", maPN) :
                new ObjectParameter("maPN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_PN", maPNParameter);
        }
    
        public virtual int xoa_PX(string maPX)
        {
            var maPXParameter = maPX != null ?
                new ObjectParameter("maPX", maPX) :
                new ObjectParameter("maPX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_PX", maPXParameter);
        }
    
        public virtual ObjectResult<xuat_CTN_Result> xuat_CTN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xuat_CTN_Result>("xuat_CTN");
        }
    
        public virtual ObjectResult<xuat_CTX_Result> xuat_CTX()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xuat_CTX_Result>("xuat_CTX");
        }
    
        public virtual ObjectResult<xuat_HH_Result> xuat_HH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xuat_HH_Result>("xuat_HH");
        }
    
        public virtual ObjectResult<xuat_NCC_Result> xuat_NCC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xuat_NCC_Result>("xuat_NCC");
        }
    
        public virtual ObjectResult<xuat_PN_Result> xuat_PN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xuat_PN_Result>("xuat_PN");
        }
    
        public virtual ObjectResult<xuat_PX_Result> xuat_PX()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xuat_PX_Result>("xuat_PX");
        }
    }
}
