//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Kho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKe
    {
        public string tenHH { get; set; }
        public string maHH { get; set; }
        public Nullable<int> sln { get; set; }
        public Nullable<int> slx { get; set; }
        public Nullable<int> conlai { get; set; }
    }
}
